// Generated by CoffeeScript 1.6.3
(function() {
  var fakeedda, http, url;

  http = require('http');

  url = require('url');

  fakeedda = require('./fakeedda');

  http.createServer(function(req, res) {
    var instances, parsedUrl, users;
    parsedUrl = url.parse(req.url);
    res.writeHead(200, {
      "Content-Type": "text/json",
      "Access-Control-Allow-Origin": "*"
    });
    if (fakeedda.matchesUserUrl('fps-perf', parsedUrl.pathname)) {
      console.log("getting users");
      users = require('./users.json');
      return res.end(JSON.stringify(users));
    } else if (fakeedda.matchesInstanceUrl('fps-perf', ['us-west-1', 'us-west-2'], parsedUrl.pathname)) {
      console.log("getting instances");
      instances = require('./instances.json');
      return res.end(JSON.stringify(instances));
    } else {
      console.log("no!" + parsedUrl.pathname);
      return res.end(JSON.stringify([]));
    }
  }).listen(8888);

}).call(this);
