// Generated by CoffeeScript 1.6.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.userUrl = function(account) {
    return "/edda/" + account + "/aws/iamUsers;_pp;_expand";
  };

  root.instanceUrl = function(account, region) {
    return '/edda/' + region + '/' + account + '/view/instances;_pp;_expand';
  };

  root.matchesUserUrl = function(account, url) {
    return root.userUrl(account) === url;
  };

  root.matchesInstanceUrl = function(account, regions, target) {
    var arr, output, r, url, urls, _i, _len;
    arr = [];
    if (regions instanceof Array) {
      arr = regions;
    } else {
      arr = [regions];
    }
    output = false;
    urls = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = arr.length; _i < _len; _i++) {
        r = arr[_i];
        _results.push(root.instanceUrl(account, r));
      }
      return _results;
    })();
    for (_i = 0, _len = urls.length; _i < _len; _i++) {
      url = urls[_i];
      output = output || target === url;
    }
    return output;
  };

}).call(this);
